name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Set version
        run: ./mvnw versions:set -DnewVersion="$(git fetch || true && git rev-list --count $GITHUB_SHA)"
      - name: Upload artifact
        run: ./mvnw --settings .github/settings.xml deploy
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}